sudo: required

language: c

env:
  global:
    - YAUL_INSTALL_ROOT=/tool-chains
    - YAUL_BUILD_ROOT=/tmp
    - YAUL_BUILD=build
  matrix:
    - YAUL_OPTION_DEV_CARTRIDGE=0 BUILD_TYPE=release
    - YAUL_OPTION_DEV_CARTRIDGE=0 BUILD_TYPE=debug

    - YAUL_OPTION_DEV_CARTRIDGE=1 BUILD_TYPE=release
    - YAUL_OPTION_DEV_CARTRIDGE=1 BUILD_TYPE=debug

    - YAUL_OPTION_DEV_CARTRIDGE=2 BUILD_TYPE=release
    - YAUL_OPTION_DEV_CARTRIDGE=2 BUILD_TYPE=debug

    - YAUL_OPTION_DEV_CARTRIDGE=0 BUILD_TYPE=tools
    - YAUL_OPTION_DEV_CARTRIDGE=1 BUILD_TYPE=tools
    - YAUL_OPTION_DEV_CARTRIDGE=2 BUILD_TYPE=tools

before_script:
  - wget -O tool-chain.tar.bz2 https://drive.google.com/uc?export=download&id=1Fk5eIC6x6y2qNBMNCtgv8ZzrS_1386kB
  - sudo mkdir /tool-chains
  - sudo tar mxvfjp tool-chain.tar.bz2 -C /tool-chains/
  - git submodule init
  - git submodule update -f

script:
  - .travis/test.sh
