# bundle exec jekyll serve -H 0.0.0.0 -P 80

theme: minima
title: Yaul
description: An open source SEGA Saturn development kit
author: Israel Jacquez
show_downloads: false

show_excerpts: false

github_username: ijacquez

header_pages:
 - getting-started.md
 - community.md
 - downloads.md
